apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pde2e-runner
  labels:
    app.kubernetes.io/version: "0.1"
    redhat.com/product: podman-desktop
    dev.lifecycle.io/phase: testing
  annotations:
    tekton.dev/pipelines.minVersion: "0.24.x"
    tekton.dev/categories: podman-desktop
    tekton.dev/tags: podman-desktop, testing
    tekton.dev/displayName: "Podman Desktop E2E Test runner"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task can setup podman machine if podman is available and run e2e test via npm task

  workspaces:
  - name: pipelines-data
  
  params:
  - name: host
  - name: username
  - name: userpassword
  - name: key
  - name: os
    default: windows
  - name: arch
    default: amd64
  - name: workspace-resources-path
  - name: image-version
    default: '0.0.3'
  - name: pd-url
    default: ""
  - name: pd-path
    default: ""
  - name: fork
    default: 'podman-desktop'
  - name: branch
    default: 'main'
  - name: ext-repo
    default: ""
  - name: ext-fork
    default: ""
  - name: ext-branch
    default: ""
  - name: ext-tests
    default: '0'
  - name: npm-target
    default: 'test:e2e'
  - name: podman-path
    default: ""
  - name: podman-initialize
    default: '1'
  - name: podman-start
    default: '1'
  - name: podman-rootful
    default: '1'
  - name: podman-user-networking
    default: '0'
  - name: env-vars
    default: "TEST_PODMAN_MACHINE=true,TEST=2"
  - name: secret-file
    default: ""
  - name: podman-provider
    default: ""
  - name: save-traces
    default: '1'
  - name: clean-machine
    default: '1'
  - name: script-paths
    default: ""
  - name: workspace-qe-subpath
    default: qe-results
  - name: results-folder
    default: results
  - name: target-cleanup
    default: 'true'

  results:
  - name: duration
  - name: junit-name
  - name: junit-path

  steps:
  - name: e2e
    image: quay.io/odockal/pde2e-runner:v$(params.image-version)-$(params.os)
    imagePullPolicy: Always
    script: |
      #!/bin/bash
      # Remove 'set -e' to allow script to handle result cleanup even if tests fail
      
      SECONDS=0
      TARGET_HOST="$(params.host)"
      TARGET_HOST_USERNAME="$(params.username)"
      TARGET_HOST_KEY_PATH="$(workspaces.pipelines-data.path)/$(params.workspace-resources-path)/$(params.key)"
      
      chmod 600 "${TARGET_HOST_KEY_PATH}"
      TARGET_FOLDER=pd-e2e
      TARGET_RESULTS="$(params.results-folder)"
      OUTPUT_FOLDER="$(workspaces.pipelines-data.path)/$(params.workspace-resources-path)/$(params.workspace-qe-subpath)"
      mkdir -p "${OUTPUT_FOLDER}"

      if [ -n "$(params.secret-file)" ]; then
        secretFile="$(workspaces.pipelines-data.path)/$(params.workspace-resources-path)/$(params.secret-file)"
        echo "Copying secret file: $(params.secret-file)"
        cp "${secretFile}" /opt/pde2e-runner/
      fi
      
      # Use escaped double quotes \" to wrap values. 
      # This is critical for Windows paths with spaces like C:\Program Files\
      if [[ "$(params.os)" == "windows" ]]; then
        cmd="${TARGET_FOLDER}/runner.ps1 "
        cmd="$cmd -targetFolder \"${TARGET_FOLDER}\" "
        cmd="$cmd -resultsFolder \"${TARGET_RESULTS}\" "
        cmd="$cmd -pdPath \"$(params.pd-path)\" "
        cmd="$cmd -pdUrl \"$(params.pd-url)\" "
        cmd="$cmd -fork \"$(params.fork)\" "
        cmd="$cmd -branch \"$(params.branch)\" "
        cmd="$cmd -extTests \"$(params.ext-tests)\" "
        [[ -n "$(params.ext-repo)" ]] && cmd="$cmd -extRepo \"$(params.ext-repo)\" "
        [[ -n "$(params.ext-fork)" ]] && cmd="$cmd -extFork \"$(params.ext-fork)\" "
        [[ -n "$(params.ext-branch)" ]] && cmd="$cmd -extBranch \"$(params.ext-branch)\" "
        cmd="$cmd -envVars \"$(params.env-vars)\" "
        cmd="$cmd -secretFile \"$(params.secret-file)\" "
        cmd="$cmd -npmTarget \"$(params.npm-target)\" "
        cmd="$cmd -podmanPath \"$(params.podman-path)\" "
        cmd="$cmd -initialize \"$(params.podman-initialize)\" "
        cmd="$cmd -start \"$(params.podman-start)\" "
        cmd="$cmd -rootful \"$(params.podman-rootful)\" "
        cmd="$cmd -userNetworking \"$(params.podman-user-networking)\" "
        [[ -n "$(params.script-paths)" ]] && cmd="$cmd -scriptPaths \"$(params.script-paths)\" "
        [[ -n "$(params.podman-provider)" ]] && cmd="$cmd -podmanProvider \"$(params.podman-provider)\" "
        cmd="$cmd -saveTraces \"$(params.save-traces)\" "
      fi

      if [[ "$(params.os)" == "darwin" ]]; then
        cmd="${TARGET_FOLDER}/runner.sh "
        cmd="$cmd --targetFolder \"${TARGET_FOLDER}\" "
        cmd="$cmd --resultsFolder \"${TARGET_RESULTS}\" "
        cmd="$cmd --pdPath \"$(params.pd-path)\" "
        [[ -n "$(params.pd-url)" ]] && cmd="$cmd --pdUrl \"$(params.pd-url)\" "
        cmd="$cmd --extTests \"$(params.ext-tests)\" "
        [[ -n "$(params.ext-repo)" ]] && cmd="$cmd --extRepo \"$(params.ext-repo)\" "
        [[ -n "$(params.ext-fork)" ]] && cmd="$cmd --extFork \"$(params.ext-fork)\" "
        [[ -n "$(params.ext-branch)" ]] && cmd="$cmd --extBranch \"$(params.ext-branch)\" "
        cmd="$cmd --envVars \"$(params.env-vars)\" "
        cmd="$cmd --secretFile \"$(params.secret-file)\" "
        cmd="$cmd --fork \"$(params.fork)\" "
        cmd="$cmd --branch \"$(params.branch)\" "
        cmd="$cmd --npmTarget \"$(params.npm-target)\" "
        [[ -n "$(params.podman-path)" ]] && cmd="$cmd --podmanPath \"$(params.podman-path)\" "
        cmd="$cmd --initialize \"$(params.podman-initialize)\" "
        cmd="$cmd --start \"$(params.podman-start)\" "
        cmd="$cmd --rootful \"$(params.podman-rootful)\" "
        [[ -n "$(params.podman-provider)" ]] && cmd="$cmd --podmanProvider \"$(params.podman-provider)\" "
        cmd="$cmd --saveTraces \"$(params.save-traces)\" "
        cmd="$cmd --cleanMachine \"$(params.clean-machine)\" "
        [[ -n "$(params.script-paths)" ]] && cmd="$cmd --scriptPaths \"$(params.script-paths)\" "
      fi
      
      echo "Composed Command: ${cmd}"

      # Exec
      . entrypoint.sh "${cmd}"

      # Results Processing
      echo -n "${SECONDS}" | tee "$(results.duration.path)"
      
      # Use a check to prevent errors if the directory is missing due to test failure
      if [ -d "${OUTPUT_FOLDER}/${TARGET_RESULTS}" ]; then
        mv "${OUTPUT_FOLDER}/${TARGET_RESULTS}/"* "${OUTPUT_FOLDER}"/ || true
        rm -rf "${OUTPUT_FOLDER}/${TARGET_RESULTS}"
      fi

      # Safely handle Junit pathing
      JUNIT_FILE=$(ls "${OUTPUT_FOLDER}"/junit*.xml 2>/dev/null | head -n 1)
      if [ -n "$JUNIT_FILE" ]; then
        echo -n "$(basename "$JUNIT_FILE")" | tee "$(results.junit-name.path)"
        echo -n "$JUNIT_FILE" | tee "$(results.junit-path.path)"
      else
        echo "No junit results found."
      fi
      
    resources:      
      requests:
        memory: "50Mi"
        cpu: "5m"
      limits:
        memory: "70Mi"
        cpu: "10m"

  sidecars:
  - name: fake-rdp
    image: quay.io/rhqp/frdp:v0.0.1
    imagePullPolicy: Always
    env:
    - name: RDP_HOST
      value: $(params.host)
    - name: RDP_USER
      value: $(params.username)
    - name: RDP_PASSWORD
      value: $(params.userpassword)
    resources:      
      requests:
        memory: "30Mi"
        cpu: "5m"
      limits:
        memory: "70Mi"
        cpu: "10m"
